name: Build, push and deploy

on:
  pull_request:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-central-1'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract release version
        run: |
          echo $GITHUB_HEAD_REF
          export "RELEASE_VERSION=$(echo ${GITHUB_HEAD_REF#release/**})"
          echo $RELEASE_VERSION

      - name: Build and push Docker image
        run: |
          docker build -t my-project:$RELEASE_VERSION . 
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY
          docker tag my-project:$RELEASE_VERSION $ECR_REPOSITORY/my-project:$RELEASE_VERSION
          docker push $ECR_REPOSITORY/my-project:$RELEASE_VERSION

      - name: Deploy helm chart
        run: |
          cd kubernetes
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name app-eks-cluster
          helm upgrade --install app-chart ./app-chart --set image.tag=$RELEASE_VERSION
        if: env.RELEASE_VERSION != ''
