name: Build, push and deploy

on:
  push:
    tags:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-central-1'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download a Terrafrom outputs
        uses: actions/download-artifact@v2
        with:
          name: terraform-outputs

      - name: Parse outputs
        run: |
          echo "HELM_ECR_REPO=$(jq -r .ecr_repository_name.helm_ecr.value outputs.json)" >> $GITHUB_ENV
          echo "IMAGE_ECR_REPO=$(jq -r .ecr_repository_name.image_ecr.value outputs.json)" >> $GITHUB_ENV
          echo "EKS_CLUSTER_NAME=$(jq -r .eks_cluster_name.value outputs.json)" >> $GITHUB_ENV

      - name: Extract versions from Chart.yaml
        run: |
          cd kubernetes/app-chart
          echo "CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')" >> $GITHUB_ENV
          echo "APP_VERSION=$(grep '^appVersion:' Chart.yaml | awk '{print $2}' | tr -d '\"')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPOSITORY }}
          docker build -t my-project:${{ env.APP_VERSION }} .
          docker tag my-project:${{ env.APP_VERSION }} ${{ vars.ECR_REPOSITORY }}/my-project:${{ env.APP_VERSION }}
          docker push ${{ vars.ECR_REPOSITORY }}/my-project:${{ env.APP_VERSION }}

      - name: Package and push Helm chart
        run: |
          cd kubernetes
          sed -i 's|image: ${{ vars.ECR_REPOSITORY }}/my-project|image: ${{ vars.ECR_REPOSITORY }}/my-project:${{ env.APP_VERSION }}|' app-chart/values.yaml
          cat app-chart/values.yaml
          helm package app-chart
          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | helm registry login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
          helm push "app-chart-${{ env.CHART_VERSION }}.tgz" oci://${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/

      - name: Install Helm chart
        run: |
          cd kubernetes
          aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name ${{ env.EKS_CLUSTER_NAME }}
          helm upgrade --install app-chart oci://${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/app-chart --version ${{ env.CHART_VERSION }}
