name: Build and push

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 695079529626.dkr.ecr.eu-central-1.amazonaws.com
          docker build -t app_ecr .
          docker tag app_ecr:latest 695079529626.dkr.ecr.eu-central-1.amazonaws.com/app_ecr:latest
          docker push 695079529626.dkr.ecr.eu-central-1.amazonaws.com/app_ecr:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
