name: Provision EKS cluster

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Terraform apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          terraform output -json > outputs.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
      - name: Upload Terraform Outputs as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-outputs
          path: terraform/outputs.json
